openedx_proversity_reports/__init__.py, openedx_proversity_reports/edxapp_wrapper/backends/course_cohort_i_v1.py, openedx_proversity_reports/edxapp_wrapper/backends/course_teams_i_v1.py, openedx_proversity_reports/edxapp_wrapper/backends/student_i_v1.py, openedx_proversity_reports/edxapp_wrapper/get_course_cohort.py, openedx_proversity_reports/edxapp_wrapper/get_course_teams.py, openedx_proversity_reports/edxapp_wrapper/get_student_library.py, openedx_proversity_reports/settings/common.py, openedx_proversity_reports/settings/production.py, openedx_proversity_reports/utils.py, setup.cfg
This PR includes the team and cohort fields to the json response.
=> Add team and cohort fields

openedx_proversity_reports/api/v0/urls.py, openedx_proversity_reports/api/v0/views.py, openedx_proversity_reports/tasks.py
Adds last page accessed report according to DATA-2 ticket.
=> DATA-2 - Adding last page accesed report.

openedx_proversity_reports/reports/last_page_accessed.py, openedx_proversity_reports/tasks.py
This PR adds additional fields to existing report and also adds a new type of report data to process.
=> DATA-24 - Adding additional fields to report.

Makefile, openedx_proversity_reports/api/v0/urls.py, openedx_proversity_reports/api/v0/views.py, openedx_proversity_reports/reports/time_spent_report.py, openedx_proversity_reports/settings/common.py, openedx_proversity_reports/settings/production.py, openedx_proversity_reports/tasks.py, requirements.in, requirements.txt, setup.py
This PR adds the time spent report backend, in order to process and generate the .csv file.
In order to test this new report you need to add to config.json this new keys and values:
"SUPPORTED_REPORTS": [
"completion_report",
"last_page_accessed",
"time_spent_report"
],
"TIME_SPENT_REPORT": {
"REPORT_URL": "/proversity-reports/api/v0/generate-time-spent-report",
"BACKEND_REPORT": "report_backend.time_spent_report:TimeSpentReportBackend"
}
=> DATA-6 - Add time spent report backend.

openedx_proversity_reports/utils.py
Create a deep copy from the root_block for every user
=> Data-28 Bug Completion report

openedx_proversity_reports/edxapp_wrapper/backends/student_i_v1.py, openedx_proversity_reports/edxapp_wrapper/get_student_library.py, openedx_proversity_reports/reports/last_page_accessed.py
This PR adds additional info such as: cohort name, teams name, user role and vertical position.
=> DATA-29 - Add additional info to last page accessed report.

openedx_proversity_reports/reports/last_page_accessed.py, openedx_proversity_reports/tasks.py, openedx_proversity_reports/utils.py
This PR adds the user role for completion report.
=> DATA-26 - Add user role to completion report.

openedx_proversity_reports/reports/time_spent_report.py
This PR adds support for tracking Google Analytics data by course unit instead of course subsection.
=> PE-373 - Adding support for unit tracking.

openedx_proversity_reports/reports/last_page_accessed.py, openedx_proversity_reports/reports/time_spent_report.py
This PR chnages the behaviour of obtaining the course structure, adding a staff user instead of student user, in order to get the entire course structure.
=> PE-373-patch-1 - Get staff user instead of student user.

openedx_proversity_reports/reports/last_page_accessed.py, openedx_proversity_reports/reports/time_spent_report.py, openedx_proversity_reports/tasks.py, openedx_proversity_reports/utils.py
This PR changes some things to the reports such as:
- Get only users with the role student for the three reports.
- Remove user role info.
- Add section name to last page accessed report.
=> DATA-37 - Report format changes.

openedx_proversity_reports/api/v0/urls.py, openedx_proversity_reports/api/v0/views.py, openedx_proversity_reports/edxapp_wrapper/backends/certificates_models_i_v1.py, openedx_proversity_reports/edxapp_wrapper/backends/course_grade_factory_i_v1.py, openedx_proversity_reports/edxapp_wrapper/get_certificates_models.py, openedx_proversity_reports/edxapp_wrapper/get_course_grade_factory.py, openedx_proversity_reports/reports/learning_tracker_report.py, openedx_proversity_reports/settings/common.py, openedx_proversity_reports/settings/production.py, openedx_proversity_reports/tasks.py, openedx_proversity_reports/utils.py
- Re factor in order to use a unique general view
- Create a new task for learning tracker metrics
- Add new backends
=> PE-423 Include learning tracker report

openedx_proversity_reports/edxapp_wrapper/backends/student_i_v1.py, openedx_proversity_reports/edxapp_wrapper/get_student_library.py, openedx_proversity_reports/middleware.py, openedx_proversity_reports/reports/learning_tracker_report.py, openedx_proversity_reports/serializers.py, openedx_proversity_reports/settings/common.py, openedx_proversity_reports/settings/production.py
Add middleware in order to set session user data.
Get session data in learning tracker report.
=> Middleware for user sessions

openedx_proversity_reports/api/v0/views.py, openedx_proversity_reports/edxapp_wrapper/backends/student_account_g_v1.py, openedx_proversity_reports/edxapp_wrapper/backends/student_i_v1.py, openedx_proversity_reports/edxapp_wrapper/get_student_account_library.py, openedx_proversity_reports/edxapp_wrapper/get_student_library.py, openedx_proversity_reports/reports/enrollment_report.py, openedx_proversity_reports/serializers.py, openedx_proversity_reports/settings/common.py, openedx_proversity_reports/settings/production.py, openedx_proversity_reports/tasks.py
Add enrollment report.
Add student account library.
Remove default values from view and add in task.
=> PE-420 - Add Enrollment report.

openedx_proversity_reports/api/v0/urls.py, openedx_proversity_reports/api/v0/views.py, openedx_proversity_reports/edxapp_wrapper/backends/course_details_g_v1.py, openedx_proversity_reports/edxapp_wrapper/get_course_details.py, openedx_proversity_reports/reports/enrollment_report.py, openedx_proversity_reports/serializers.py, openedx_proversity_reports/settings/common.py, openedx_proversity_reports/settings/production.py
This PR adds the API to interact with the SalesforceContactId model.
This PR only adds the POST endpoint.
=> PE-421 - Salesforce contact id API.

openedx_proversity_reports/api/v0/urls.py, openedx_proversity_reports/api/v0/views.py, openedx_proversity_reports/reports/activity_completion_report.py, openedx_proversity_reports/serializers.py, openedx_proversity_reports/utils.py
This PR adds a new API endpoint to get the activity completion data per user instead of per course.
=> DATA-44 Adding API endpoint to get the activity completion data per user.

openedx_proversity_reports/reports/activity_completion_report.py
This PR improves the response time of the activity completion per user API.
=> PE-639 - Improving the activity completion API response.

openedx_proversity_reports/reports/time_spent_report_per_user.py
This modifies the time spent per user report to get the names and positions of the sections and subsections within the course.
Also changes the filter to obtain chapter, sequential and vertical blocks instead of components.
=> PE-699 - Modifications to the time spent per user report.

openedx_proversity_reports/reports/backend/enrollment_per_site_report.py
This PR solves a problem with the number of registered users on site.
=> PE-888 - Patch-1 - Fixing an inconsistency of data of registered users.

openedx_proversity_reports/edxapp_wrapper/backends/course_content_i_v1.py, openedx_proversity_reports/edxapp_wrapper/get_course_content.py, openedx_proversity_reports/reports/backend/enrollment_per_site_report.py, openedx_proversity_reports/settings/common.py, openedx_proversity_reports/settings/production.py, openedx_proversity_reports/tasks.py
This PR adds the course's display name to the enrollment per site report API data.
=> PE-925 - Adding course's display name to the enrollment per site report.

openedx_proversity_reports/google_services/bigquery_module.py, openedx_proversity_reports/reports/backend/enrollment_per_site_report.py, openedx_proversity_reports/tasks.py
This PR adds the time spent value from Google Big Query to the enrollment per site report data.
=> PE-929 - Add time spent to the enrollment per site report.

openedx_proversity_reports/reports/backend/enrollment_per_site_report.py, openedx_proversity_reports/tasks.py
This PR removes the date from the query of Google Big Query.
=> PE-929-patch-1 - Removing date from the Google BigQuery.

openedx_proversity_reports/edxapp_wrapper/backends/courseware_i_v1.py, openedx_proversity_reports/edxapp_wrapper/get_courseware_library.py, openedx_proversity_reports/reports/backend/enrollment_per_site_report.py
This PR adds the date of first access to course to the enrollment per site API endpoint.
=> PE-939 - Adding date of first access to course for the enrollment per site report.

openedx_proversity_reports/reports/last_login_report.py, openedx_proversity_reports/settings/common.py, openedx_proversity_reports/tasks.py, setup.py
This PR adds the backend for the last login report.
Fixes a problem with the installation of the dependencies.
=> PE-477 - Adding last login report.

openedx_proversity_reports/google_services/bigquery_module.py
This PR solves a problem with the course id value by replacing these characters ('/', '.', '-') with ('_') to avoid problems with the Google BigQuery name notation.
=> PE-975.1 - Replace problematic characters in the course id value.

openedx_proversity_reports/tasks.py
This PR adds some default options to the enrollment per site task.
=> PAE-145 - Add default options to enrollment per site task.
